export const PERMISSIONS = [
  "dashboard.read",
  "products.read",
  "products.write",
  "categories.read",
  "categories.write",
  "collections.write",
  "attributes.write",
  "inventory.read",
  "inventory.write",
  "media.read",
  "media.write",
  "orders.read",
  "orders.update",
  "returns.read",
  "returns.manage",
  "customers.read",
  "customers.write",
  "coupons.read",
  "coupons.write",
  "reviews.read",
  "reviews.moderate",
  "content.read",
  "content.write",
  "navigation.write",
  "blog.write",
  "filters.write",
  "seo.write",
  "settings.read",
  "settings.write",
  "integrations.manage",
  "users.read",
  "users.manage",
  "roles.manage",
  "audit.read",
] as const;
export type PermissionKey = (typeof PERMISSIONS)[number];

const all = [...PERMISSIONS] as PermissionKey[];
const readOnly = all.filter((p) => p.endsWith(".read"));

export const DEFAULT_ROLES: Record<
  string,
  { name: string; description: string; permissions: PermissionKey[] }
> = {
  SUPER_ADMIN: {
    name: "Super Admin",
    description: "Full access, including users and roles",
    permissions: all,
  },
  ADMIN: {
    name: "Admin",
    description: "Full store management except role definitions",
    permissions: all.filter((p) => p !== "roles.manage"),
  },
  CATALOG_MANAGER: {
    name: "Catalog Manager",
    description: "Products, categories, inventory, media",
    permissions: [
      "dashboard.read",
      "products.read",
      "products.write",
      "categories.read",
      "categories.write",
      "collections.write",
      "attributes.write",
      "inventory.read",
      "inventory.write",
      "media.read",
      "media.write",
      "filters.write",
      "reviews.read",
    ],
  },
  ORDER_MANAGER: {
    name: "Order Manager",
    description: "Orders, returns, customers",
    permissions: [
      "dashboard.read",
      "orders.read",
      "orders.update",
      "returns.read",
      "returns.manage",
      "customers.read",
      "products.read",
      "inventory.read",
      "coupons.read",
    ],
  },
  CONTENT_MANAGER: {
    name: "Content Manager",
    description: "Pages, navigation, blog, media, SEO",
    permissions: [
      "dashboard.read",
      "content.read",
      "content.write",
      "navigation.write",
      "blog.write",
      "seo.write",
      "media.read",
      "media.write",
      "reviews.read",
      "reviews.moderate",
      "products.read",
      "categories.read",
    ],
  },
  SUPPORT: {
    name: "Support",
    description: "Read-only plus review moderation",
    permissions: [...readOnly, "reviews.moderate"],
  },
};
